CrudNetC5/CrudNetC5/Models/ErrorViewModel.cs
using System;

namespace CrudNetC5.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CrudNetC5/CrudNetC5/Models/Libro.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CrudNetC5.Models
{
    public class Libro
    {
        [Key]
        public int Id { get; set; }

        [Required (ErrorMessage ="El titulo es obligatorio")]
        [StringLength(50, ErrorMessage ="El {0} debe ser al menos {2} y máximo {1} caracteres")]
        [Display(Name ="Título")]
        public string Titulo { get; set; }

        [Required(ErrorMessage ="La descripción es requerida")]
        [StringLength(50, ErrorMessage = "El {0} debe ser al menos {2} y máximo {1} caracteres")]
        [Display(Name ="Descripción")]
        public string Descripcion { get; set; }

        [Required(ErrorMessage ="La fecha de publicación es obligatoria")]
        [DataType(DataType.Date)]
        [Display(Name ="Fecha de lanzamiento")]
        public DateTime Fecha { get; set; }

        [Required(ErrorMessage ="El nombre del autor es requerido")]
        public string Autor { get; set; }
        [Display(Name ="Precio")]
        [Required(ErrorMessage ="El precio es requerido")]
        public int precio { get; set; }
    }
}

CrudNetC5/CrudNetC5/Controllers/HomeController.cs
using CrudNetC5.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CrudNetC5.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CrudNetC5/CrudNetC5/Controllers/LibrosController.cs
using CrudNetC5.Data;
using CrudNetC5.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CrudNetC5.Controllers
{
    public class LibrosController : Controller
    {
        private readonly AplicationDbContext _context;

        public LibrosController(AplicationDbContext context)
        {
            _context = context;
        }
        
        //Http get Index
        public IActionResult Index()
        {
            IEnumerable<Libro> ListaLibros = _context.Libro;
            return View(ListaLibros);
        }

        //Http get Create
        public IActionResult Create()
        {
            
            return View();
        }


        ////Http post Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Libro libro)
        {
            ///Validando el modelo
            if (ModelState.IsValid)
            {
                //agrega el modelo a la instancia de la base de datos
                _context.Libro.Add(libro);
                //guarda los cambios
                _context.SaveChanges();

                TempData["mensaje"] = "El libro se ha creado correctamente";

                return RedirectToAction("Index");//vuelve a redireccionar al index del controlador
            }
            return View();
        }

        //Http get Edit
        public IActionResult Edit(int? id)//puede ser nulo
        {
            if (id==null || id==0)
            {
                return NotFound();
            }

            var libro = _context.Libro.Find(id);
            if (libro==null)
            {
                return NotFound();
            }


            return View(libro);
        }
        ////Http post Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Libro libro)
        {
            ///Validando el modelo
            if (ModelState.IsValid)
            {
                //agrega el modelo a la instancia de la base de datos
                _context.Libro.Update(libro);
                //guarda los cambios
                _context.SaveChanges();

                TempData["mensaje"] = "El libro se ha actualizado correctamente";

                return RedirectToAction("Index");//vuelve a redireccionar al index del controlador
            }
            return View();
        }

        //Http get Delete
        public IActionResult Delete(int? id)//puede ser nulo
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var libro = _context.Libro.Find(id);
            if (libro == null)
            {
                return NotFound();
            }


            return View(libro);
        }
        ///Http post Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteLibro(int? id)
        {


            var libro = _context.Libro.Find(id);
            if (libro==null)
            {
                return NotFound();
            }
            _context.Libro.Remove(libro);
                //guarda los cambios
                _context.SaveChanges();

                TempData["mensaje"] = "El libro ha sido eliminado correctamente";

                return RedirectToAction("Index");//vuelve a redireccionar al index del controlador
       
        }
    }
}

CrudNetC5/CrudNetC5/Views/Libros/Create.cshtml
@model CrudNetC5.Models.Libro
@{
    ViewData["Title"] = "Crear nuevo libro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Crear nuevo libro</h3>
        </div>
    </div>
        <div class="row">
            <div class="col-sm-10">
                <form method="post" asp-action="Create">

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>@*Valdacion del lado del servidor*@
                    <!--Validaciones del lado del cliente-->
                    <div class="form-group">
                        <label asp-for="Titulo" class="control-label"></label>
                        <input asp-for="Titulo" class="form-control" />
                        <span asp-validation-for="Titulo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Descripcion" class="control-label"></label>
                        <input asp-for="Descripcion" class="form-control" />
                        <span asp-validation-for="Descripcion" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Fecha" class="control-label"></label>
                        <input asp-for="Fecha" class="form-control" />
                        <span asp-validation-for="Fecha" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Autor" class="control-label"></label>
                        <input asp-for="Autor" class="form-control" />
                        <span asp-validation-for="Autor" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="precio" class="control-label"></label>
                        <input asp-for="precio" class="form-control" />
                        <span asp-validation-for="precio" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary" value="Guardar" />
                    </div>
                </form>
            </div>
    </div>
</div>

@section Scripts{
                @{ <partial name="_ValidationScriptsPartial" />}
            }

CrudNetC5/CrudNetC5/Views/Libros/Delete.cshtml
@model CrudNetC5.Models.Libro
@{
    ViewData["Title"] = "Editar libro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Eliminar registro</h3>
        </div>
    </div>
        <div class="row">
            <div class="col-sm-10">
                <form method="post" asp-action="DeleteLibro">

                    <input type="hidden" asp-for="Id"/> @*Guardar el id oculto*@

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>@*Valdacion del lado del servidor*@
                    <!--Validaciones del lado del cliente-->
                    <div class="form-group">
                        <label asp-for="Titulo" class="control-label"></label>
                        <input asp-for="Titulo" class="form-control" disabled/>
                        <span asp-validation-for="Titulo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Descripcion" class="control-label"></label>
                        <input asp-for="Descripcion" class="form-control" disabled/>
                        <span asp-validation-for="Descripcion" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Fecha" class="control-label"></label>
                        <input asp-for="Fecha" class="form-control" disabled/>
                        <span asp-validation-for="Fecha" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Autor" class="control-label"></label>
                        <input asp-for="Autor" class="form-control" disabled/>
                        <span asp-validation-for="Autor" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="precio" class="control-label"></label>
                        <input asp-for="precio" class="form-control" disabled/>
                        <span asp-validation-for="precio" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary" value="Eliminar" />
                    </div>
                </form>
            </div>
    </div>
</div>

@section Scripts{
                @{ <partial name="_ValidationScriptsPartial" />}
            }

CrudNetC5/CrudNetC5/Views/Libros/Edit.cshtml
@model CrudNetC5.Models.Libro
@{
    ViewData["Title"] = "Editar libro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Crear nuevo libro</h3>
        </div>
    </div>
        <div class="row">
            <div class="col-sm-10">
                <form method="post" asp-action="Edit">

                    <input type="hidden" asp-for="Id"/> @*Guardar el id oculto*@

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>@*Valdacion del lado del servidor*@
                    <!--Validaciones del lado del cliente-->
                    <div class="form-group">
                        <label asp-for="Titulo" class="control-label"></label>
                        <input asp-for="Titulo" class="form-control" />
                        <span asp-validation-for="Titulo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Descripcion" class="control-label"></label>
                        <input asp-for="Descripcion" class="form-control" />
                        <span asp-validation-for="Descripcion" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Fecha" class="control-label"></label>
                        <input asp-for="Fecha" class="form-control" />
                        <span asp-validation-for="Fecha" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Autor" class="control-label"></label>
                        <input asp-for="Autor" class="form-control" />
                        <span asp-validation-for="Autor" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="precio" class="control-label"></label>
                        <input asp-for="precio" class="form-control" />
                        <span asp-validation-for="precio" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary" value="Actualizar" />
                    </div>
                </form>
            </div>
    </div>
</div>

@section Scripts{
                @{ <partial name="_ValidationScriptsPartial" />}
            }

CrudNetC5/CrudNetC5/Views/Libros/Index.cshtml
@model IEnumerable<CrudNetC5.Models.Libro>
@{
    ViewData["Title"] = "Lista de libros";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    @if (TempData["mensaje"]!=null)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            @TempData["mensaje"];
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">
                    &times;
                </span>
            </button>
        </div>
    }
    <div class="row">
        <div class="col-sm-6">
            <h3>Lista de Libros</h3>
        </div>
        <div class="col-sm-6">
            <a class="btn btn-success d-block" asp-action="Create" asp-controller="Libros">Agregar nuevo libro</a>
        </div>
    </div>
    <div class="row">
        @if (Model.Count()>0)//Si el modelo tiene al menos un registro
            {
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <td>@Html.DisplayNameFor(modelo => modelo.Id)</td><!--Trae el titulo del campo seleccionado-->
                    <td>@Html.DisplayNameFor(modelo => modelo.Titulo)</td><!--Trae el titulo del campo seleccionado-->
                    <td>@Html.DisplayNameFor(modelo => modelo.Descripcion)</td><!--Trae el titulo del campo seleccionado-->
                    <td>@Html.DisplayNameFor(modelo => modelo.Fecha)</td><!--Trae el titulo del campo seleccionado-->
                    <td>@Html.DisplayNameFor(modelo => modelo.Autor)</td><!--Trae el titulo del campo seleccionado-->
                    <td>@Html.DisplayNameFor(modelo => modelo.precio)</td><!--Trae el titulo del campo seleccionado-->
                    <td>Acciones</td>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Titulo</td>
                        <td>@item.Descripcion</td>
                        <td>@item.Fecha</td>
                        <td>@item.Autor</td>
                        <td>@item.precio</td>
                        <td>
                            <a asp-controller="Libros" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">Editar</a>
                            <a asp-controller="Libros" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Eliminar</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
            }
            else
            {
                <p>No tenemos registros</p>
            }
    </div>
</div>

CrudNetC5/CrudNetC5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CrudNetC5</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CrudNetC5</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Libros" asp-action="index">Libros</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CrudNetC5 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>